version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: sudo apt update --fix-missing
      - run: sudo apt install -y gcc-avr binutils-avr avr-libc
      - run: make
      - store_artifacts:
          path: grbl.hex

workflows:
  version: 2
  build:
    jobs:
      - build
