version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: sudo apt update --fix-missing
      - run: sudo apt install -y gcc-avr binutils-avr avr-libc srecord
      - run: make grbl.bootloader.hex
      - store_artifacts:
          path: grbl.hex
      - store_artifacts:
          path: grbl.bootloader.hex

workflows:
  version: 2
  build:
    jobs:
      - build
